---
name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  verify:
    uses: JamesWoolfenden/.github/.github/workflows/terraform-verify-gcp.yml@main
    with:
      service_account: terraform-gcp-appengine@pike-477416.iam.gserviceaccount.com
